Problem Statement 1: Write a Python program to multiply a 𝑀 × 𝑁 matrix by 𝑁 × 𝐴 matrix and
create a real matrix product.

Example:

Input:
Enter value M: 5
Enter value N: 3
Enter value A: 2

Output:

First array:
[[0.92825664 0.62790011 0.80130199]
[0.64283876 0.16558409 0.54573802]
[0.04319311 0.80229079 0.72512472]
[0.8005622 0.98844625 0.6982794 ]
[0.46600134 0.51451131 0.6415925 ]]

Second array:
[[0.31898348 0.49050318]
[0.53845583 0.48259499]
[0.89102055 0.35539951]]

Dot product of two arrays:
[[1.34817154 1.04311661]
[0.78047845 0.58917954]
[1.09187707 0.66607684]
[1.40978205 1.11786566]
[0.99736045 0.70489738]]

In [ ]:
import numpy as np
import random as rd

def list_array_conversion(in_list):
  """
  list_array_conversion(list):
  This function accepts a list of strings as a parameter and returns a one dimensional integer array.

  sample_output:
  in_list=['1', '2', '3', '4', '5', '6', '7', '8', '9']
  list_array_conversion(in_list)
  [1 2 3 4 5 6 7 8 9]
  """
  for i in range(len(in_list)):
    in_list[i]=float(in_list[i])
  return np.array(in_list)

def generate_random_float_list(random_length):
  """
  generate_random_float_list(random_length):
  This function accepts length as a parameter and returns a list of random numbers between 1 to 100.

  sample_output:
  generate_random_list(4)
  generate_random_list(random_length)
  [22 34 10 7]
  """
  random_list=[]
  while random_length!=0:
    i=rd.random()
    random_list.append(i)
    random_length=random_length-1
  return random_list


# Accepting the dimensions of both the matrices
m=int(input("Enter value M: "))
n=int(input("Enter value N: "))
a=int(input("Enter value A: "))

user_choice=input("Type 'Y' to provide custom input. Otherwise, type 'N' to continue with random numbers: ")
if user_choice.lower()=='y':
  # Accepting the list of input values and storing them as a separate element using the split function
  input_list1=input(f"Enter {m*n} elements: ").split()

  if len(input_list1)>(m*n) or len(input_list1)<(m*n):
    raise Exception("You did not entered the required number of elements in given range. Program Ended..!")

  input_list2=input(f"Enter {n*a} elements: ").split()
  if len(input_list2)>(n*a) or len(input_list2)<(n*a):
    raise Exception("You did not entered the required number of elements in given range. Program Ended..!")

  input_list1=list_array_conversion(input_list1)
  input_list2=list_array_conversion(input_list2)

else:
  input_list1=generate_random_float_list(m*n)
  input_list2=generate_random_float_list(n*a)

#Using the numpy.reshape function to convert the list into an array and store as per the respective dimensions
first_array=np.reshape(input_list1,(m,n))
second_array=np.reshape(input_list2,(n,a))

#Printing the Matrices and their Dot product
print("\nFirst Array:\n",first_array)
print("\nSecond Array:\n",second_array)
print("\nDot product of two arrays:\n",np.dot(first_array, second_array))


Enter value M: 5
Enter value N: 3
Enter value A: 2
Type 'Y' to provide custom input. Otherwise, type 'N' to continue with random numbers: y
Enter 15 elements: 0.92825664 0.62790011 0.80130199 0.64283876 0.16558409 0.54573802 0.04319311 0.80229079 0.72512472 0.8005622 0.98844625 0.6982794 0.46600134 0.51451131 0.6415925
Enter 6 elements: 0.31898348 0.49050318 0.53845583 0.48259499 0.89102055 0.35539951

First Array:
 [[0.92825664 0.62790011 0.80130199]
 [0.64283876 0.16558409 0.54573802]
 [0.04319311 0.80229079 0.72512472]
 [0.8005622  0.98844625 0.6982794 ]
 [0.46600134 0.51451131 0.6415925 ]]

Second Array:
 [[0.31898348 0.49050318]
 [0.53845583 0.48259499]
 [0.89102055 0.35539951]]

Dot product of two arrays:
 [[1.34817155 1.04311662]
 [0.78047845 0.58917953]
 [1.09187707 0.66607684]
 [1.40978206 1.11786567]
 [0.99736045 0.70489738]]


Problem Statement 2: Write a NumPy program to check if each element of an array of your choice is composed of digits, lower case letters, and upper case letters only.

Hint: You can use isdigit(),islower(), and isupper() function.

Example:

 Input: Original Array:

 ['Python' 'PHP' 'JS' 'Examples' 'html5' '5']

3

 Output: Digits only = [False False False False False True]

 Lower cases only = [False False False False True
False]

 Upper cases only = [False True True False False
False]

In [ ]:
import numpy as np

# Accepting a custom length input from the user by asking the length of the input
length=int(input("How many elements you want to enter in the array : "))
# Storing the user input sequence in a list as a separate element using split() function
input_list=input(f"Enter {length} elements separated by space: ").split()
if len(input_list)<length:
  raise Exception("You did not entered the elements in the given range..!")
# Converting the input list to a an numpy array
input_array=np.array(input_list)

# Checking each element of the array whether it is a digit only, a lowercase or an uppercase element and storing them into a new array
digits_only = np.char.isdigit(input_array)
lowercases_only = np.char.islower(input_array)
uppercases_only = np.char.isupper(input_array)

#printing the final output to console
print("\nOriginal Array:", input_array)
print("\nDigits only =", digits_only )
print("\nLower cases only =", lowercases_only )
print("\nUpper cases only =", uppercases_only )

How many elements you want to enter in the array : 6
Enter 6 elements separated by space: Python PHP JS Examples html5 5

Original Array: ['Python' 'PHP' 'JS' 'Examples' 'html5' '5']

Digits only = [False False False False False  True]

Lower cases only = [False False False False  True False]

Upper cases only = [False  True  True False False False]


Problem Statement 3: Write a program that reads two space-separated positive integers 𝑋 and
𝑌 as input and perform the following tasks:
Tasks to be performed:
1. Create a list (lst1) starting at one (1) with 16 elements at a step of 𝑋
2. Create a list (lst2) starting at one (1) with 16 elements at a step of 𝑌
3. Create two NumPy arrays np1 and np2 using lst1 and lst2 respectively
4. Reshape both the NumPy arrays to (4,4)
5. Create a new np array (np3) with values obtained by subtracting both the arrays (np1 -
np2)
6. Print all the elements of np3 in a single dimension list like the format as shown below:
a. [n0 n1 n2 n3 n4 n5 n6 n7 n8]
Example:
Input:
7 9
Output:
[ 0 -2 -4 -6 -8 -10 -12 -14 -16 -18 -20 -22 -24 -26 -28 -30]



In [ ]:
import numpy as np


def accept(num):
  """
  accept(num):
  This is an accept function which takes one parameter num. It will return a list of 16 elements with the step value of num

  Sample output:
  accept(3)
  list=[1, 4, 7, 10, 13, 16, 19, 22, 25, 28, 31, 34, 37, 40, 43, 46]

  """
  lst=[]
  for i in range(1,(16*num),num):
    lst.append(i)
  return lst

#Accepting the numbers from user and storing the in a list called numbers
numbers=input("Please enter two numbers (for e.g: 3 4):").split()
lst1=accept(int(numbers[0]))
lst2=accept(int(numbers[1]))

#Creating a numpy array from the input list
np1=np.array(lst1)
np2=np.array(lst2)

#Reshaping the array into a 4 [row] 4 [column], two dimensional array using numpy.reshape function and passing the array with required dimension
np1=np.reshape(np1,(4,4))
np2=np.reshape(np2,(4,4))

#Subtracting numpy array1 from numpy array2 and storing the output into a third array called np3
np3=(np1-np2)

#Creating a view of np3 array to print all the elements of np3 in a single dimension list like the format using the numpy.ravel() function.
np3=np.ravel(np3)

#Printing the final output to console
print("\n",np3)

Please enter two numbers (for e.g: 3 4):7 9

 [  0  -2  -4  -6  -8 -10 -12 -14 -16 -18 -20 -22 -24 -26 -28 -30]


Problem Statement 4: Write a Python program that takes two integer-NumPy arrays, 𝑃 and 𝑄 of
shape [3 ∗ 3] and perform the following task:
Task to be performed:
Print the element-wise difference of the matrix 𝑃 and 𝑄 (𝑃 − 𝑄).
Example:
Input:
23 56 87 3 6 96 4 6 78
12 34 54 7 2 54 6 2 78
Output:
[[11 22 33]
[-4 4 42]
[-2 4 0]]

In [ ]:
import numpy as np
import random as rd

def list_array_conversion(in_list):
  """
  list_array_conversion(list):
  This function accepts a list of strings as a parameter and returns a one dimensional integer array.

  sample_output:
  in_list=['1', '2', '3', '4', '5', '6', '7', '8', '9']
  list_array_conversion(in_list)
  [1 2 3 4 5 6 7 8 9]

  """
  for i in range(len(in_list)):
    in_list[i]=int(in_list[i])
  return np.array(in_list)

def generate_random_list(random_length):
  """
  generate_random_list(random_length):
  This function accepts length as a parameter and returns a list of random numbers between 1 to 100.

  sample_output:
  generate_random_list(4)
  generate_random_list(random_length)
  [22 34 10 7]
  """
  random_list=[]
  while random_length!=0:
    i=rd.randint(0,99)
    random_list.append(i)
    random_length=random_length-1
  return random_list


#Accepting user's choice whether to do the array subtraction using random numbers or by user's choice
choice=input("Type 'y' to provide custom input. Otherwise type 'n' to continue the random calculation: ")

if choice.lower()=='y':
  #Accepting the array dimensions from the user
  in_length=int(input("Enter the dimension of your choice for the array (Max array size=4): "))
  if in_length > 4:
    raise Exception("You did not specify the length in the given range. Program ended.")
  elif in_length==0:
    raise Exception("Array dimension cannot be zero.")

  # Accepting the input from user for a fixed length entered by the user
  in_list1=input(f"Enter {in_length**2} elements separated by space for first array: ").split()

  if len(in_list1)<in_length**2:
    raise Exception("You did not specify the elements in the given range. Program ended.")

  in_list2=input(f"Enter {in_length**2} elements separated by space for second array: ").split()

  if len(in_list2)<in_length**2:
    raise Exception("You did not specify the elements in the given range. Program ended.")

  in_list1=list_array_conversion(in_list1)
  in_list2=list_array_conversion(in_list2)

else:
  #Taking random inputs using the random.randint() function
  in_length=rd.randint(1,4)
  in_list1=generate_random_list(in_length**2)
  in_list2=generate_random_list(in_length**2)
  print("\nRandomly generated output:")

#Reshape the array to the accepted dimension
p=np.reshape(in_list1,(in_length,in_length))
q=np.reshape(in_list2,(in_length,in_length))

#Performing element wise subtraction and storing the output to another array r
r=p-q

#print the final output
print("\nP:\n",p)
print("\nQ:\n",q)
print("\n[P - Q] Output:\n",r)

Type 'y' to provide custom input. Otherwise type 'n' to continue the random calculation: y
Enter the dimension of your choice for the array (Max array size=4): 3
Enter 9 elements separated by space for first array: 23 56 87 3 6 96 4 6 78
Enter 9 elements separated by space for second array: 12 34 54 7 2 54 6 2 78

P:
 [[23 56 87]
 [ 3  6 96]
 [ 4  6 78]]

Q:
 [[12 34 54]
 [ 7  2 54]
 [ 6  2 78]]

[P - Q] Output:
 [[11 22 33]
 [-4  4 42]
 [-2  4  0]]
